### PR TITLE
Add word "സായാഹ്നം"

### PR DESCRIPTION
**Pull request by subins2000**

### CODE REVIEW

**Comment by knadh** [comment]
I don't have a system that loads this to olam.in directly, but will implement that sometime soon as well.

**Comment by subins2000** [comment]
@knadh Cool, a webhook automation will be awesome.

This could be a good activity for hacktoberfest. We can expand it a lot. But conflicts would be a problem with the `id` parameter tho. Perhaps remove that from entering manually into YAML and auto generate it ?

**Comment by knadh** [comment]
Yep, [dictmaker](https://github.com/knadh/dictmaker) has a GUID concept. We can get rid of the legacy numeric IDs in the Datuk corpus and replace them with random UUIDs.

Loading the corpus into dictmaker's table schema should be easy. Just need to port [mlphone](https://github.com/knadh/mlphone) to Go and write a tokenizer to get the dictionary site up.

**Comment by subins2000** [comment]
@knadh I see that mlphone is similar to ml2en library. I can give it a try to port to Go. I have only did some basic stuff in Go, but I'd like to work on it more. Shall I give a go at it ? Or have you started any work on porting it ?

**Comment by subins2000** [comment]
@knadh I just tried [mlphone](https://nadh.in/code/mlphone/), but why does it replace "കുട്ടേട്ടന്‍" with "കുട്ടേട്ടന്" ? Is that how it's supposed to work ?

**Comment by knadh** [comment]
You can give it a shot. It should be straight forward. I did [knphone](https://github.com/knadh/knphone) for Kannada in Go.

> @knadh I just tried mlphone, but why does it replace "കുട്ടേട്ടന്‍" with "കുട്ടേട്ടന്" ? Is that how it's supposed to work ?

That seems to be a rendering issue with the demo pages. mlphone takes a Malayalam word and produces 3 alphanumeric keys.
`കുട്ടേട്ടന്‍ = KTTN | KTTN | K5T26T2N`

**Pull request merged**
